baseURL: http://localhost:1313/
languageCode: en-us
title: Randy Bedi
theme: PaperMod


params:
    cover:
        linkFullImages: true

    homeInfoParams:
        title: "Randy Bedi"
        
       
        

    socialIcons: 
        - name: github
          url: "https://github.com/RandeepB21"
        - name: linkedin
          url: "https://www.linkedin.com/in/randeep-bedi"
        - name: email
          url: mailto:r4bedi@uwaterloo.ca
menu:  
    main:
        -   identifier: about me
            name: About Me
            url: /aboutme/
            weight: 10
        -   identifier: projects
            name: Projects
            url: /projects/
            weight: 20
        -   identifier: interests
            name: Interests
            url: /interests/
            weight: 30

disableAnchoredHeadings: true
disableSpecial1stPost: true